### ISSUE TITLE
Question for internal functions

### ISSUE THREAD

**Issue by ozum** [eradman/pg-safeupdate#6]
Hi,

Thanks for this useful extension.

I’m the developer of a simple open-source PostgreSQL extension. My extension pg_datatye_password (https://github.com/ozum/pg_datatype_password) creates a new data type for passwords that encrypts and adds salts to a given input.

Currently, I'm using a trigger for insert/update, because I’m not familiar with C and the internal functions of pg. It would be much better if the input function for custom types (`passwordin (pg_catalog.cstring)`) encrypts and returns the value instead of the trigger.

This function just needs to crypt input value and return it encrypted as the following pseudo-code:

```
return crypt(<---- INPUT OF THE COLUMN ---->, gen_salt('bf', 10));
```

I will appreciate it if you could help. Sorry, this is not the place for asking this, but after using your extension, I thought you can help.

Best,

**Comment by eradman** [comment]
Hi, this question is off topic for pg-safeupdate, but I see where you're trying to go.

I doubt it would be a good idea to create a hook for every INSERT/UPDATE since you would have to look up the types of every column. Instead you want a way to write a filter that is attached to a custom type--I don't know how this can be done in PostgreSQL.

The solution you have already is also probably best since you don't need to install a shared library when postgres is started, you can define the triggers at any time.

**Comment by ozum** [comment]
Thanks for the advice @eradman. Sorry again for posting here.

**Comment by eradman** [comment]
Not a problem! Feel free to send me an e-mail any time
